baseURL = 'http://cmt1910.github.io/blog'
languageCode = 'ja'
title = 'ちょこみんとの雑記帳'
theme = "PaperMod"

[params]
env = "production"

[params.homeInfoParams]
Title = "ちょこみんと"
Content = "ゲームや映像、デザインを作っています"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/cmt1910"

[[params.socialIcons]]
name = "github"
url = "https://github.com/cmt1910"